### ISSUE TITLE
Aktivierung TinyMCE

### ISSUE THREAD

**Issue by tniebergall** [MetaModels/attribute_translatedlongtext#6]
Wenn man in einem MetaModel für ein Attribut vom Typ translatedlongtext den TinyMCE aktiviert, wird diese Konfiguration für alle Attribute vom Typ translatedlongtext übernommen.

**Comment by discordier** [comment]
Sollte seit https://github.com/MetaModels/core/commit/7ed0c7c2b6880feef7aef6a4f48e700da82c4d59 nicht mehr so sein, hast du eine alte Version?

**Comment by tniebergall** [comment]
Hab die neuste TNG via composer 85826a73

**Comment by discordier** [comment]
Und es betrifft NUR den tinyMCE im translatedlongtext?

**Comment by xantippe** [comment]
@tniebergall ist das Ticket noch aktuell?

**Comment by tniebergall** [comment]
Ist erledigt
